### PR TITLE
Add CI, Eslint

### LINKED ISSUE #31: Setup CI in GitHub Actions

### PR DESCRIPTION
**Pull request by DimitarSD**
Fixes #31

Current Challenges / Outlines:
- As far as I can tell, there are 2 tests still failing inside of: test_update_funding_round.test.js
- Tests cannot pass without Airtable. It requires to modify interact w/ table.
- Tests are running in github actions, and we cannot add these manual overrides in there as-is.

Airtable Testing - Design Outline
- Before each test, Airtable should be a certain state.
- After updating the Airtable, we should be validating that the values are correct.

Changes proposed in this PR:
- [x] Add CI (running github actions)
- [x] Add ESlint and fix errors
- [x] Sort out any final eslint issue (refer to issue #21)
- [x] Switch from mocha to jest
- [ ] Mocking Data - All tests that are running in GH Actions have their own mock data.
- [x] GH Actions - Get all tests passing.
- [x] GH Actions - Airtable tests will only run locally. **2 tests in GH Actions right now are dependant on Airtable will be disabled during GH Actions.**

Local testing - How To:
- [ ] Most tests will execute against local / mock data.
- [ ] Some tests will execute against Airtable (which requires you to be connected).
- [ ] If you are testing against your own Airtable (local), you will have to re-implement it so GH Actions tests can pass (global).

Further Improvements:
- [ ] Update GH Actions so it can run tests against Airtable
- [ ] Update tests so they are all working w/ a pre-populated airtable.
- [ ] Update tests to do pre-test setup & post-test validation

### CODE REVIEW

**Comment by KatunaNorbert** [comment]
I think you should add `.test.` in `test_project_summary.js` and `test_update_funding_round.js` files name.
And also there are some tests outside the `test` too.

**Comment by DimitarSD** [comment]
After our last discussion, there are a couple of things to do in order to finish with this PR

- [ ] Fix failing tests by mocking the data we use for them
- [ ] Sort out any final eslint issue (refer to issue #21)
- [ ] Get all tests passing in GitHub actions

**Comment by idiom-bytes** [comment]
Hi Dimo, could you list all of the tests that are failing in your comments?

**Comment by KatunaNorbert** [comment]
Can you also update the test Airtable view so we have all the tests passing locally?

**Comment by DimitarSD** [comment]
@KatunaNorbert are you referring to the API keys for Airtable? Testing all tests locally is dependant on your local `.env` file which should contain all needed keys for Airtable (and to your table).

**Comment by KatunaNorbert** [comment]
Yes, I mean setting up a test Airtable which we can use by BaseId in env when running the tests locally so all the test will pass.

**Comment by DimitarSD** [comment]
A staging table will be added but this is another issue (https://github.com/oceanprotocol/DAOBot/issues/47). 

The staging table needs to include everything we need in order for all tests to pass. However, this will take time. That's why I've included a quick "fix" (`GACTIONS_ENV` env variable) that will not run the tests that are dependent on Airtable and that are currently failing in the GitHub actions. But it will keep running them locally. 

The tests in GitHub actions are using my Airtable (base id and API keys), and since they run automatically we can't update the table on the go manually. If some tests are failing in your local environment make sure that when you test against your table the needed data is added/updated/changed accordingly.

We'll fix the issue with running tests against Airtable (and make them pass) but it won't be in this PR.

**Comment by AnaLoznianu** [comment]
@DimitarSD Removing myself as a reviewer as I don't have the tech knowledge to review this PR. I'll defer this one to @KatunaNorbert, @claudiaHash and @trizin

**Review by trizin — APPROVED** [review]

**Review by KatunaNorbert — APPROVED** [review]

**Pull request merged**
