### PR TITLE
Add a new proposal state for projects that want to withdraw

### LINKED ISSUE #40: Add a new [Proposal State] option for projects that want to withdraw
From Alex Napheys:
"Having a way to distinguish that a project has decided to quit/withdrawal is also important. we should create an option in the parameters in airtable for labeling "project withdrawal".
This is different from participants rejecting/voting no on a proposal"

### PR DESCRIPTION
**Pull request by claudiaHash**
Fixes #40 .

Changes proposed in this PR:

- add a new proposal state for projects that want to withdraw
- exclude withdrawn projects from compute winning proposals
- exclude withdrawn projects from compute burned funds

### CODE REVIEW

**Comment by idiom-bytes** [comment]
Hi Claudia, just looking at the changes, and it looks correct.
I re-ran CI/CD after timeout was implemented.

I believe this could be merged.

**Comment by claudiaHash** [comment]
> I believe this could be merged.

Just checked again if proposals are filtered correctly by their state, and it seem so. I think it could be merged. I'll add the new "Withdrawn" proposal state option into main db.

**Comment by KatunaNorbert** [comment]
Is the proposal going to appear in Snapshot and receive votes if is in the `Withdrawn` state?

**Comment by claudiaHash** [comment]
> Is the proposal going to appear in Snapshot and receive votes if is in the `Withdrawn` state?

No. A team can announce the withdrawal of its proposal before it appears in Snapshot

**Comment by KatunaNorbert** [comment]
Then why do we need to filter it, it shouldn't affect the granting process?

**Review by KatunaNorbert — APPROVED** [review]

**Comment by idiom-bytes** [comment]
It's also great for prosperity sake! :raised_hands: 

Thank you both for being inquisitive about whether it's required or not!

**Pull request merged**
